In [1]:
import numpy as np


In [2]:
x=np.random.normal(0,1,size=1000000)

In [4]:
np.min(x)

-4.698044721142729

In [5]:
np.argmin(x)#最小值的索引位置

575404

In [6]:
np.argmax(x)

273143

In [7]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)#乱序处理
x

array([ 0,  8,  3, 15,  4, 12, 10,  7, 13,  2,  5,  9, 11, 14,  1,  6])

In [11]:
np.sort(x)#排序不修改x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x.sort()#排序修改x
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
X=np.random.randint(10,size=(4,4))
X

array([[3, 9, 7, 5],
       [5, 4, 2, 4],
       [7, 7, 7, 4],
       [7, 8, 8, 9]])

In [15]:
np.sort(X)

array([[3, 5, 7, 9],
       [2, 4, 4, 5],
       [4, 7, 7, 7],
       [7, 8, 8, 9]])

In [16]:
np.sort(X,axis=1)

array([[3, 5, 7, 9],
       [2, 4, 4, 5],
       [4, 7, 7, 7],
       [7, 8, 8, 9]])

In [17]:
np.sort(X,axis=0)

array([[3, 4, 2, 4],
       [5, 7, 7, 4],
       [7, 8, 7, 5],
       [7, 9, 8, 9]])

In [20]:
x=np.arange(16)
np.random.shuffle(x)#乱序处理

In [21]:
np.partition(x,3)#快速排序一趟

array([ 0,  1,  2,  3,  5,  4,  6, 11, 10,  8,  7, 12,  9, 13, 15, 14])