In [1]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10).dtype


dtype('float64')

In [4]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(shape=(3,5),fill_value=6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [9]:
# random
np.random.randint(0,10)

2

In [10]:
np.random.randint(0,10,10)

array([1, 9, 1, 1, 4, 7, 1, 8, 9, 2])

In [16]:
x=np.random.randint(4,8,size=(3,5))
x

array([[5, 6, 7, 4, 6],
       [6, 6, 4, 7, 7],
       [5, 6, 6, 7, 5]])

In [12]:
np.random.random(10)

array([0.64538715, 0.96523419, 0.88419735, 0.75976331, 0.79732109,
       0.04898566, 0.56444126, 0.76666553, 0.80542737, 0.57731741])

In [13]:
np.random.random((3,5))

array([[0.43360985, 0.12197047, 0.46780998, 0.10954407, 0.65645146],
       [0.64854011, 0.97047068, 0.01917864, 0.78636664, 0.34945146],
       [0.56204116, 0.51399484, 0.04541494, 0.00226147, 0.19869686]])

In [14]:
np.random.normal(10,100)

-37.96732966582944

In [19]:
x[0,:3]

array([5, 6, 7])

In [21]:
x[:2,3:]

array([[4, 6],
       [7, 7]])

In [24]:
x[1:]

array([[6, 6, 4, 7, 7],
       [5, 6, 6, 7, 5]])

In [27]:
x[2,2]=3
x

array([[5, 6, 7, 4, 6],
       [6, 6, 4, 7, 7],
       [5, 6, 3, 7, 5]])