In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [3]:
#合并
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z=np.array([666,666,666])
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [5]:
A=np.array([[1,2,3],
            [4,5,6]])
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [9]:
B=np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [10]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [16]:
#分割
x=np.arange(10)
x1,x2,x3=np.split(x,[3,7])

In [17]:
x1

array([0, 1, 2])

In [18]:
x2

array([3, 4, 5, 6])

In [19]:
x1,x2=np.split(x,[5])
x1

array([0, 1, 2, 3, 4])

In [20]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
A1,A2=np.split(A,[2])
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
A1,A2=np.split(A,[2],axis=1)
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])