In [1]:
import numpy as np


In [2]:
L=np.random.random(100)

In [3]:
np.sum(L)

49.379426128720176

In [4]:
x=np.arange(16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
np.sum(x,axis=0)

array([24, 28, 32, 36])

In [6]:
np.sum(x,axis=1)

array([ 6, 22, 38, 54])