In [1]:
import numpy as np

In [2]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
x[3:9:2]

array([3, 5, 7])

In [6]:
index=[3,5,8]
x[index]

array([3, 5, 8])

In [8]:
index=np.array([[0,2],
               [1,3]])
x[index]

array([[0, 2],
       [1, 3]])

In [9]:
X=x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
row=np.array([0,1,2])
col=np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [12]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [14]:
col=[True,False,True,True]
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [17]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [18]:
np.sum(x<=3)

4

In [19]:
np.all(x>0)#判断是否所有元素大于0

False

In [20]:
X=np.random.randint(10,size=(4,4))
X

array([[9, 0, 0, 2],
       [9, 2, 3, 8],
       [0, 5, 9, 3],
       [5, 4, 1, 8]])

In [23]:
np.all(X>1,axis=0)

array([False, False, False,  True])