In [1]:
import numpy as np

In [4]:
n=10
L=[i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
%%time
A=[]
for e in L:
    A.append(2*e)
A

Wall time: 3 ms


In [8]:
%%time
L=np.arange(n)
A=2*L
A

Wall time: 0 ns


In [9]:
x=np.arange(1,16).reshape((3,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
x+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [11]:
x**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [12]:
np.power(3,x)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [13]:
#多个矩阵运算
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [14]:
B=np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [15]:
A*B #numpy中都是对应元素之间运算

array([[ 0, 10],
       [20, 30]])

In [16]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [17]:
A.T

array([[0, 2],
       [1, 3]])